export default {
    "2da95": "Law, Government, and Politics",
    "d4bfb": "Arts (studio)",
    "19242": "Communications",
    "3e182": "Exchanges and Trips",
    "f95ce": "Food",
    "09573": "Computers and Programming",
    "b8e72": "Building and Design",
    "4e92b": "Education, Learning, and Behavior",
    "096ab": "Arts (performing)",
    "10456": "Writing and Literature",
    "d7574": "Law, Government, or Politics",
    "67d2a": "Health",
    "48624": "Science",
    "a4b61": "History and Culture",
    "3566e": "Medicine",
    "4ae3f": "Education, learning, and behavior",
    "fe75a": "Retail",
    "0ed82": "Service",
    "498b6": "Veterinary Medicine",
    "fd893": "Mathematics",
    "ea0a1": "Farming",
    "68eef": "Business and Finance",
    "dbc24": "Exchanges and trips",
    "a12c6": "Computers and Design",
    "a3857": "Writing and Culture",
    "e5462": "Athletics"
}
