name: Build Docker Image and Upload to Registry

on:
  push:
    branches: [ "main", "test-8/16/24" ] # using test-8/16/24 to test the workflow
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
